kind: PersistentVolume
apiVersion: v1
metadata:
  name: gf-user-db-pv-volume
  namespace: qa
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgres/gf_user"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gf-user-db-pv-claim
  namespace: qa
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gf-user-db-deployment
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gf-user-db-service
  template:
    metadata:
      labels:
        app: gf-user-db-service
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 5432
          args:
            - -c
            - hba_file=/etc/postgresql/gf-user/pg_hba.conf
            - -c
            - config_file=/etc/postgresql/gf-user/postgresql.conf
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: gf-user-secret
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gf-user-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gf-user-secret
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: gf-user-db-storage
            - mountPath: /etc/postgresql/gf-user
              name: gf-user-config-storage
      volumes:
        - name: gf-user-db-storage
          persistentVolumeClaim:
            claimName: gf-user-db-pv-claim
        - name: gf-user-config-storage
          configMap:
            name: gf-user-db-config
---
apiVersion: v1
kind: Service
metadata:
  name: gf-user-db-service
  namespace: qa
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30007
  selector:
   app: gf-user-db-service

# kubectl delete service gf-user-db-service 
# kubectl delete deployment gf-user-db-deployment
# kubectl delete persistentvolumeclaim gf-user-db-pv-claim
# kubectl delete persistentvolume gf-user-db-pv-volume
# minikube service gf-user-db-service -n qa