apiVersion: v1
kind: Namespace
metadata:
  name: qa
---
apiVersion: v1
kind: Service
metadata:
  name: gf-user-service
  namespace: qa
spec:
  type: NodePort
  selector:
    app: gf-user
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gf-user-deployment
  namespace: qa
  labels:
    app: gf-user
  annotations:
    rollout: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gf-user
  template:
    metadata:
      labels:
        app: gf-user
    spec:
      containers:
        - name: golang
          image: mucunga90/gf-user:qa
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
          envFrom:
            - secretRef:
                name: gf-user-secret

# kubectl delete service gf-user-service 
# kubectl delete deployment gf-user-deployment
# kubectl delete persistentvolumeclaim gf-user-service-pv-claim
# kubectl delete persistentvolume gf-user-service-pv-volume
