CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	identifier TEXT NOT NULL,	
	password TEXT NOT NULL,
	status VARCHAR(20) NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted BOOLEAN NOT NULL default(false),
	enabled BOOLEAN NOT NULL default(false),
	UNIQUE(identifier),
	UNIQUE(identifier, password)
);