CREATE TABLE IF NOT EXISTS session (
	id BIGSERIAL PRIMARY KEY,
	userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	channel VARCHAR(10) NOT NULL,
	remoteIP VARCHAR(50) NOT NULL,
	userAgent VARCHAR(200) NOT NULL,
	token VARCHAR(500) NOT NULL,
	expiredDate TIMESTAMP NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(userid)
);