CREATE TABLE IF NOT EXISTS session (
	id BIGSERIAL PRIMARY KEY,
	userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	channel VARCHAR(10) NOT NULL,
	remoteIP VARCHAR(50) NOT NULL,
	expiredDate TIMESTAMP NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	active INTEGER default (1),
	UNIQUE(userid)
);