CREATE TABLE IF NOT EXISTS otp (
	id BIGSERIAL PRIMARY KEY,
	channel VARCHAR(10) NOT NULL,
	token TEXT NOT NULL,
	expiredDate TIMESTAMP NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	verified BOOLEAN NOT NULL default(false),
	active BOOLEAN NOT NULL default(true),
	UNIQUE(token)
);