CREATE TABLE IF NOT EXISTS otp (
	id SERIAL PRIMARY KEY,
	userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	token FLOAT NOT NULL,
	expiredDate TIMESTAMP NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	verified BOOLEAN NOT NULL default(false),
	UNIQUE(id, userid),
	UNIQUE(token)
);