CREATE TABLE IF NOT EXISTS notify (
	id SERIAL PRIMARY KEY,
	templateId INTEGER NULL,	
	channelId INTEGER NOT NULL,
	operation VARCHAR(50) NOT NULL,
	uri VARCHAR(100) NOT NULL,
	recipient VARCHAR(100) NOT NULL,
	createdBy BIGINT NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	params TEXT[] NULL,
	status VARCHAR(50) NOT NULL,
	sent BOOLEAN NOT NULL default(false)
);