CREATE TABLE IF NOT EXISTS permission (
	id BIGSERIAL PRIMARY KEY,
	roleId INTEGER NOT NULL REFERENCES role(id) ON DELETE CASCADE,
	actionId INTEGER NOT NULL REFERENCES action(id) ON DELETE CASCADE,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(id),
	UNIQUE(roleId, actionId)
);