CREATE TABLE IF NOT EXISTS client (
	id BIGSERIAL PRIMARY KEY,
	email VARCHAR(100) NOT NULL,
	clientId VARCHAR(100) NOT NULL,
	secret VARCHAR(100) NOT NULL,
	failedAttempts INTEGER default (0),
	lastAttempt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expiredDate TIMESTAMP NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted BOOLEAN NOT NULL default(false),
	enabled BOOLEAN NOT NULL default(true),
	UNIQUE(email),
	UNIQUE(clientId),
	UNIQUE(secret)	
);
