kind: PersistentVolume
apiVersion: v1
metadata:
  name: gf-user-db-pv-volume
  namespace: stage
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/greatfocus/gf_user_db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gf-user-db-pv-claim
  namespace: stage
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gf-user-db-service
  namespace: stage
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30007
  selector:
   app: gf-user-db-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gf-user-db-service
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gf-user-db-service
  template:
    metadata:
      labels:
        app: gf-user-db-service
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: gf-user-secret
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gf-user-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gf-user-secret
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: gf-user-db-storage
      volumes:
        - name: gf-user-db-storage
          persistentVolumeClaim:
            claimName: gf-user-db-pv-claim

# kubectl delete service gf-user-db-service 
# kubectl delete statefulset gf-user-db-service
# kubectl delete persistentvolumeclaim gf-user-db-pv-claim
# kubectl delete persistentvolume gf-user-db-pv-volume
# minikube service gf-user-db-service -n stage