### get person
GET  http://localhost:5001/user/person?userId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MDU1MTAxOTksInJvbGUiOiJDdXN0b21lciIsInVzZXJfaWQiOjIzMTd9.TsDpuZjc5jKB5-dQlRkerYfTxEey0CnXen5DNEqnDfo


### update person
PUT  http://localhost:5001/user/person
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MDU1MTAxOTksInJvbGUiOiJDdXN0b21lciIsInVzZXJfaWQiOjIzMTd9.TsDpuZjc5jKB5-dQlRkerYfTxEey0CnXen5DNEqnDfo

{
    "id": 1,
    "userId": 1,
    "countryId": 1,
    "firstName": "John",
    "middleName": "Peter",
    "lastName": "Mucunga",
    "mobileNumber": "0780904371",
    "idNumber": "27496388"
}

### create person
POST http://localhost:5001/user/person
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MDU1MTAxOTksInJvbGUiOiJDdXN0b21lciIsInVzZXJfaWQiOjIzMTd9.TsDpuZjc5jKB5-dQlRkerYfTxEey0CnXen5DNEqnDfo

{
    "userId": 2143,
    "countryId": 1,
    "firstName": "Flavian",
    "middleName": "Wanjiru",
    "lastName": "Nderitu",
    "mobileNumber": "0780904372",
    "idNumber": "27496389"
}

### contact
POST http://localhost:5001/user/contact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MDU1MTAxOTksInJvbGUiOiJDdXN0b21lciIsInVzZXJfaWQiOjIzMTd9.TsDpuZjc5jKB5-dQlRkerYfTxEey0CnXen5DNEqnDfo

{
	"name": "John Peter",
	"email": "mucunga90@gmail.com",
	"message": "Test message"
}


