### get person
GET  http://localhost:5001/user/person?userId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MDU5NTc2NzksInJvbGUiOiJDdXN0b21lciIsInVzZXJfaWQiOjIzNTl9.v9dzy9cnzdl4XVfyOnek6T8hUggwZZGwS_OQTi574RQ


### update person
PUT  http://localhost:5001/user/person
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MDU5NTc2NzksInJvbGUiOiJDdXN0b21lciIsInVzZXJfaWQiOjIzNTl9.v9dzy9cnzdl4XVfyOnek6T8hUggwZZGwS_OQTi574RQ

{
    "id": 223,
    "userId": 2359,
    "countryId": 1,
    "firstName": "John",
    "middleName": "Peter",
    "lastName": "Adrian",
    "mobileNumber": "0780904373",
    "idNumber": "27496390"
}

### create person
POST http://localhost:5001/user/person
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MDU5NTc2NzksInJvbGUiOiJDdXN0b21lciIsInVzZXJfaWQiOjIzNTl9.v9dzy9cnzdl4XVfyOnek6T8hUggwZZGwS_OQTi574RQ

{
    "userId": 2359,
    "countryId": 1,
    "firstName": "John",
    "middleName": "Peter",
    "lastName": "Adrian",
    "mobileNumber": "0780904373",
    "idNumber": "27496390"
}

### contact
POST http://localhost:5001/user/contact
Content-Type: application/json

{
	"name": "John Peter",
	"email": "mucunga90@gmail.com",
	"message": "Test message"
}


