@hostname = 127.0.0.1
@port = 5002
@host = {{hostname}}:{{port}}
@contentType = application/json
@bearer = nil


### User Login
# @name userLogin
POST http://{{host}}/user/login HTTP/1.1
Content-Type: {{contentType}}

{
	"email": "muthurimixphone@gmail.com",
	"password": "1234"
}


### create client
# @name getPerson
@bearer = {{userLogin.response.body.jwt}}
GET http://{{host}}/user/person?userId=1
Content-Type: {{contentType}}
Authorization: Bearer {{bearer}}


### update person
# @name updatePerson
@bearer = {{userLogin.response.body.jwt}}
PUT  http://{{host}}/user/person
Content-Type: {{contentType}}
Authorization: Bearer {{bearer}}

{
    "id": 1,
    "userId": 1,
    "countryId": 1,
    "firstName": "John",
    "middleName": "Peter",
    "lastName": "Mucunga",
    "mobileNumber": "0780904371",
    "idNumber": "27496388"
}

### create person
# @name createPerson
@bearer = {{userLogin.response.body.jwt}}
POST  http://{{host}}/user/person
Content-Type: {{contentType}}
Authorization: Bearer {{bearer}}

{
    "userId": 2,
    "countryId": 1,
    "firstName": "John",
    "middleName": "Peter",
    "lastName": "Adrian",
    "mobileNumber": "0780904372",
    "idNumber": "27496389"
}

### contact
# @name contact
POST http://{{host}}/user/contact
Content-Type: application/json

{
	"name": "John Peter",
	"email": "mucunga90@gmail.com",
	"message": "Test message"
}


