@host = qa.localhost.com
@contentType = application/json
@bearer = nil


### create user
# @name createUser
POST https://{{host}}/user/register
Content-Type: {{contentType}}

{
	"email": "mucunga90@gmail.com",
	"password": "1234"
}


### user token
# @name userToken
POST https://{{host}}/user/token
Content-Type: {{contentType}}

{
	"email": "mucunga90@gmail.com",
	"token": 17791
}


### login
# @name login
POST https://{{host}}/user/login
Content-Type: {{contentType}}

{
	"email": "mucunga90@gmail.com",
	"password": "1234"
}


### forgot password
# @name forgotPassword
POST https://{{host}}/user/forgotpassword
Content-Type: {{contentType}}

{
	"email": "mucunga90@gmail.com"
}


### get users
# @name getusers
@bearer = {{login.response.body.jwt}}
GET https://{{host}}/user/users?lastId=20
Content-Type: {{contentType}}
Authorization: Bearer {{bearer}}


### get user
# @name getuser
@bearer = {{login.response.body.jwt}}
GET https://{{host}}/user/users?id=7
Content-Type: {{contentType}}
Authorization: Bearer {{bearer}}

