apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: Service
metadata:
  name: gf-user-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: gf-user
  ports:
    - port: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gf-user-api-deployment
  namespace: prod
  labels:
    app: gf-user
  annotations:
    rollout: ""
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gf-user
  template:
    metadata:
      labels:
        app: gf-user
    spec:
      containers:
        - name: golang
          image: mucunga90/gf-user:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: gf-user-secret

# kubectl delete service gf-user-service 
# kubectl delete deployment gf-user-api-deployment
# kubectl delete persistentvolumeclaim gf-user-service-pv-claim
# kubectl delete persistentvolume gf-user-service-pv-volume
